### PR TITLE
Move window function pre-project creation to DAG canonicalization.

### LINKED ISSUE #541: Window function used in QueryBuilder fails to execute
Window function usage might lead to an error when multifragment input is used.

### LINKED ISSUE #543: Bug in reproduction of H2O Groupby Q8
During my reproduction of groupby Q8 from H2O benchmark on 5GB datasets there is a bug in pyhdk. 
https://duckdb.org/2023/04/14/h2oai.html

The error message is 
```
Traceback (most recent call last):
  File "/localdisk/ekrivov/db-benchmark-ilya/pyhdk/bug.py", line 27, in <module>
    ans = tmp.filter(tmp.ref("row_no") < 3).proj("id6", "v3").run()
  File "_builder.pyx", line 687, in pyhdk._builder.QueryNode.run
  File "_sql.pyx", line 213, in pyhdk._sql.RelAlgExecutor.execute
RuntimeError: Only single fragment tables supported for window functions for now
```

Source code:
```
import os
import pyhdk


src_grp = os.path.join("data", 'G1_1e8_1e2_0_0' + ".csv")

hdk = pyhdk.init(enable_cpu_groupby_multifrag_kernels=True)
x = hdk.import_csv(
    src_grp,
    schema={
        "id1": "dict",
        "id2": "dict",
        "id3": "dict",
        "id4": "int32",
        "id5": "int32",
        "id6": "int32",
        "v1": "int32",
        "v2": "int32",
        "v3": "fp64",
    },
)
tmp = x.proj(
    "id6",
    "v3",
    row_no=hdk.row_number().over(x.ref("id6")).order_by((x.ref("v3"), "desc")),
)
ans = tmp.filter(tmp.ref("row_no") < 3).proj("id6", "v3").run()
print(ans.shape, flush=True)
```

### PR DESCRIPTION
**Pull request by ienkovich**
Move DAG transformation for window functions we use in `RelAlgDagBuilder` to `canonizeQuery` so that it's applied to both Calcite and QueryBuilder generated queries. Some minor functions were moved to the IR module.

Resolves #541
Resolves #543

### CODE REVIEW

File: omniscidb/QueryOptimizer/CanonizeQuery.cpp [hunk 1]
```diff
@@ -351,10 +351,127 @@ void expandCompoundAggregates(QueryDag& dag) {
...
+  // Any applied transformation always increases number of nodes.
+  if (node_list.size() != nodes.size()) {
+    nodes.assign(node_list.begin(), node_list.end());
+    dag.setNodes(std::move(nodes));
+  }
+}
+
 }  // namespace
 
 void canonizeQuery(QueryDag& dag) {
```
Comment (alexbaden) [inline omniscidb/QueryOptimizer/CanonizeQuery.cpp:472]: I should have realized this before - but should this be `canonicalizeQuery`?

**Review by alexbaden — APPROVED** [review]

File: omniscidb/QueryOptimizer/CanonizeQuery.cpp (hunk 1 above)
Comment (ienkovich) [reply omniscidb/QueryOptimizer/CanonizeQuery.cpp:472]: Oops, sure it should.
